version: "3.8"

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "5000:5000" # Maps host port 5000 to container port 5000
    environment:
      - NODE_ENV=development
      - PORT=5000
      - MONGO_URI=mongodb://mongo:27017/mern_database
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - mongo
    restart: always

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000" # Maps host port 3000 to container port 3000
    volumes:
      - ./src:/usr/src/app/src
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=development
    stdin_open: true
    tty: true
    restart: always

  mongo:
    image: mongo:5.0 # Adjust the version if necessary
    container_name: mongo
    ports:
      - "27017:27017" # Exposes MongoDB on port 27017
    volumes:
      - mongo-data:/data/db # Data persistence

volumes:
  mongo-data:
